/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aca.fasilkomunsri.ai.sistempakarkulit.AcaFasilkomunsriAISistemPakarKulit.view;

import aca.fasilkomunsri.ai.sistempakarkulit.AcaFasilkomunsriAISistemPakarKulit.model.CF;

/**
 *
 * @author HP
 */
public class kuisioner extends javax.swing.JFrame {
    String Nama;
    String JK;
    double CFR1, CFR2, CFR3, CFR4, CFR5, CFR6, CFR7, CFR8, CFR9, CFR10, CFR11, CFR12, CFR13, CFR14, CFR15, CFR16, CFR17, CFR18, CFR19, CFR20;
    double gkNormal, gkBerminyak, gkKering, gkKombinasi, gkSensitif;
    /**
     * Creates new form kuisioner1
     */
    public kuisioner() {
        initComponents();
    }
    public kuisioner (String nama, String jk){
        this.Nama = nama;
        this.JK = jk;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        R01 = new javax.swing.ButtonGroup();
        R02 = new javax.swing.ButtonGroup();
        R03 = new javax.swing.ButtonGroup();
        R04 = new javax.swing.ButtonGroup();
        R05 = new javax.swing.ButtonGroup();
        R06 = new javax.swing.ButtonGroup();
        R07 = new javax.swing.ButtonGroup();
        R08 = new javax.swing.ButtonGroup();
        R09 = new javax.swing.ButtonGroup();
        R10 = new javax.swing.ButtonGroup();
        R11 = new javax.swing.ButtonGroup();
        R12 = new javax.swing.ButtonGroup();
        R13 = new javax.swing.ButtonGroup();
        R14 = new javax.swing.ButtonGroup();
        R15 = new javax.swing.ButtonGroup();
        R16 = new javax.swing.ButtonGroup();
        R17 = new javax.swing.ButtonGroup();
        R18 = new javax.swing.ButtonGroup();
        R19 = new javax.swing.ButtonGroup();
        R20 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        A0 = new javax.swing.JRadioButton();
        A1 = new javax.swing.JRadioButton();
        A2 = new javax.swing.JRadioButton();
        A3 = new javax.swing.JRadioButton();
        A4 = new javax.swing.JRadioButton();
        B0 = new javax.swing.JRadioButton();
        B1 = new javax.swing.JRadioButton();
        B2 = new javax.swing.JRadioButton();
        B3 = new javax.swing.JRadioButton();
        B4 = new javax.swing.JRadioButton();
        C0 = new javax.swing.JRadioButton();
        C1 = new javax.swing.JRadioButton();
        C2 = new javax.swing.JRadioButton();
        C3 = new javax.swing.JRadioButton();
        C4 = new javax.swing.JRadioButton();
        D0 = new javax.swing.JRadioButton();
        D1 = new javax.swing.JRadioButton();
        D2 = new javax.swing.JRadioButton();
        D3 = new javax.swing.JRadioButton();
        D4 = new javax.swing.JRadioButton();
        E0 = new javax.swing.JRadioButton();
        E1 = new javax.swing.JRadioButton();
        E2 = new javax.swing.JRadioButton();
        E3 = new javax.swing.JRadioButton();
        E4 = new javax.swing.JRadioButton();
        F0 = new javax.swing.JRadioButton();
        F1 = new javax.swing.JRadioButton();
        F2 = new javax.swing.JRadioButton();
        F3 = new javax.swing.JRadioButton();
        F4 = new javax.swing.JRadioButton();
        G0 = new javax.swing.JRadioButton();
        G1 = new javax.swing.JRadioButton();
        G2 = new javax.swing.JRadioButton();
        G3 = new javax.swing.JRadioButton();
        G4 = new javax.swing.JRadioButton();
        H0 = new javax.swing.JRadioButton();
        H1 = new javax.swing.JRadioButton();
        H2 = new javax.swing.JRadioButton();
        H3 = new javax.swing.JRadioButton();
        H4 = new javax.swing.JRadioButton();
        I0 = new javax.swing.JRadioButton();
        I1 = new javax.swing.JRadioButton();
        I2 = new javax.swing.JRadioButton();
        I3 = new javax.swing.JRadioButton();
        I4 = new javax.swing.JRadioButton();
        J0 = new javax.swing.JRadioButton();
        J1 = new javax.swing.JRadioButton();
        J2 = new javax.swing.JRadioButton();
        J3 = new javax.swing.JRadioButton();
        J4 = new javax.swing.JRadioButton();
        K0 = new javax.swing.JRadioButton();
        K1 = new javax.swing.JRadioButton();
        K2 = new javax.swing.JRadioButton();
        K3 = new javax.swing.JRadioButton();
        K4 = new javax.swing.JRadioButton();
        L0 = new javax.swing.JRadioButton();
        L1 = new javax.swing.JRadioButton();
        L2 = new javax.swing.JRadioButton();
        L3 = new javax.swing.JRadioButton();
        L4 = new javax.swing.JRadioButton();
        M0 = new javax.swing.JRadioButton();
        M1 = new javax.swing.JRadioButton();
        M2 = new javax.swing.JRadioButton();
        M3 = new javax.swing.JRadioButton();
        M4 = new javax.swing.JRadioButton();
        N0 = new javax.swing.JRadioButton();
        N1 = new javax.swing.JRadioButton();
        N2 = new javax.swing.JRadioButton();
        N3 = new javax.swing.JRadioButton();
        N4 = new javax.swing.JRadioButton();
        O0 = new javax.swing.JRadioButton();
        O1 = new javax.swing.JRadioButton();
        O2 = new javax.swing.JRadioButton();
        O3 = new javax.swing.JRadioButton();
        O4 = new javax.swing.JRadioButton();
        P0 = new javax.swing.JRadioButton();
        P1 = new javax.swing.JRadioButton();
        P2 = new javax.swing.JRadioButton();
        P3 = new javax.swing.JRadioButton();
        P4 = new javax.swing.JRadioButton();
        Q0 = new javax.swing.JRadioButton();
        Q1 = new javax.swing.JRadioButton();
        Q2 = new javax.swing.JRadioButton();
        Q3 = new javax.swing.JRadioButton();
        Q4 = new javax.swing.JRadioButton();
        R0 = new javax.swing.JRadioButton();
        R1 = new javax.swing.JRadioButton();
        R2 = new javax.swing.JRadioButton();
        R3 = new javax.swing.JRadioButton();
        R4 = new javax.swing.JRadioButton();
        S0 = new javax.swing.JRadioButton();
        S1 = new javax.swing.JRadioButton();
        S2 = new javax.swing.JRadioButton();
        S3 = new javax.swing.JRadioButton();
        S4 = new javax.swing.JRadioButton();
        T0 = new javax.swing.JRadioButton();
        T4 = new javax.swing.JRadioButton();
        T2 = new javax.swing.JRadioButton();
        T3 = new javax.swing.JRadioButton();
        T1 = new javax.swing.JRadioButton();
        result = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("KUISIONER");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Ket: 0 = Sangat Tidak Setuju, 1 = Tidak Setuju, 2 = Cukup Setuju, 3 = Setuju, 4 = Sangat Setuju ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("1. Tidak Berminyak");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("2. Segar dan Halus");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("3. Bahan-Bahan Kosmetik Mudah Menempel dikulit");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("4. Terlihat sehat");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("5. Tidak berjerawat");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("6. Mudah dalam memilih Kosmetik");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("7. Pori-pori kulit besar terutama di area hidung, pipi, dagu");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("8. Kulit di bagian wajah terlihat mengkilat");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("9. Sering ditumbuhi jerawat");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("10. Kulit kelihatan kering sekali");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("11. Pori-pori halus");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("12. Tekstur kulit wajah tipis");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("13. Cepat menampakkan kerutan-kerutan");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("14. Sebagian kulit kelihatan berminyak");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("15. Sebagian kulit kelihatan kering");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("16. Kadang berjerawat");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("17. Susah mendapat hasil polesan kosmetik yang sempurna");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("18. Mudah alergi");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("19. Mudah iritasi dan terluka");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("20. Kulit mudah terlihat kemerahan");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setText("0  1  2  3  4");

        R01.add(A0);
        A0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A0ActionPerformed(evt);
            }
        });

        R01.add(A1);

        R01.add(A2);

        R01.add(A3);

        R01.add(A4);

        R02.add(B0);
        B0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0ActionPerformed(evt);
            }
        });

        R02.add(B1);

        R02.add(B2);

        R02.add(B3);

        R02.add(B4);

        R03.add(C0);
        C0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C0ActionPerformed(evt);
            }
        });

        R03.add(C1);

        R03.add(C2);

        R03.add(C3);

        R03.add(C4);

        R04.add(D0);
        D0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D0ActionPerformed(evt);
            }
        });

        R04.add(D1);

        R04.add(D2);

        R04.add(D3);

        R04.add(D4);

        R05.add(E0);
        E0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E0ActionPerformed(evt);
            }
        });

        R05.add(E1);

        R05.add(E2);

        R05.add(E3);

        R05.add(E4);

        R06.add(F0);
        F0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F0ActionPerformed(evt);
            }
        });

        R06.add(F1);

        R06.add(F2);

        R06.add(F3);

        R06.add(F4);

        R07.add(G0);
        G0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G0ActionPerformed(evt);
            }
        });

        R07.add(G1);

        R07.add(G2);

        R07.add(G3);

        R07.add(G4);

        R08.add(H0);
        H0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H0ActionPerformed(evt);
            }
        });

        R08.add(H1);

        R08.add(H2);

        R08.add(H3);

        R08.add(H4);

        R09.add(I0);
        I0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I0ActionPerformed(evt);
            }
        });

        R09.add(I1);

        R09.add(I2);

        R09.add(I3);

        R09.add(I4);

        R10.add(J0);
        J0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J0ActionPerformed(evt);
            }
        });

        R10.add(J1);

        R10.add(J2);

        R10.add(J3);

        R10.add(J4);

        R11.add(K0);
        K0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K0ActionPerformed(evt);
            }
        });

        R11.add(K1);

        R11.add(K2);

        R11.add(K3);

        R11.add(K4);

        R12.add(L0);
        L0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L0ActionPerformed(evt);
            }
        });

        R12.add(L1);

        R12.add(L2);

        R12.add(L3);

        R12.add(L4);

        R13.add(M0);
        M0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M0ActionPerformed(evt);
            }
        });

        R13.add(M1);

        R13.add(M2);

        R13.add(M3);

        R13.add(M4);

        R14.add(N0);
        N0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0ActionPerformed(evt);
            }
        });

        R14.add(N1);

        R14.add(N2);

        R14.add(N3);

        R14.add(N4);

        R15.add(O0);
        O0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O0ActionPerformed(evt);
            }
        });

        R15.add(O1);

        R15.add(O2);

        R15.add(O3);

        R15.add(O4);

        R16.add(P0);
        P0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P0ActionPerformed(evt);
            }
        });

        R16.add(P1);

        R16.add(P2);

        R16.add(P3);

        R16.add(P4);

        R17.add(Q0);
        Q0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q0ActionPerformed(evt);
            }
        });

        R17.add(Q1);

        R17.add(Q2);

        R17.add(Q3);

        R17.add(Q4);

        R18.add(R0);
        R0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R0ActionPerformed(evt);
            }
        });

        R18.add(R1);

        R18.add(R2);

        R18.add(R3);

        R18.add(R4);

        R19.add(S0);
        S0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S0ActionPerformed(evt);
            }
        });

        R19.add(S1);

        R19.add(S2);

        R19.add(S3);

        R19.add(S4);

        R20.add(T0);
        T0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T0ActionPerformed(evt);
            }
        });

        R20.add(T4);

        R20.add(T2);

        R20.add(T3);

        R20.add(T1);

        result.setText("result");
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)))))))))))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A0)
                                .addGap(9, 9, 9)
                                .addComponent(A1)
                                .addGap(9, 9, 9)
                                .addComponent(A2)
                                .addGap(9, 9, 9)
                                .addComponent(A3)
                                .addGap(9, 9, 9)
                                .addComponent(A4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B0)
                                .addGap(9, 9, 9)
                                .addComponent(B1)
                                .addGap(9, 9, 9)
                                .addComponent(B2)
                                .addGap(9, 9, 9)
                                .addComponent(B3)
                                .addGap(9, 9, 9)
                                .addComponent(B4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(C0)
                                .addGap(9, 9, 9)
                                .addComponent(C1)
                                .addGap(9, 9, 9)
                                .addComponent(C2)
                                .addGap(9, 9, 9)
                                .addComponent(C3)
                                .addGap(9, 9, 9)
                                .addComponent(C4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(D0)
                                .addGap(9, 9, 9)
                                .addComponent(D1)
                                .addGap(9, 9, 9)
                                .addComponent(D2)
                                .addGap(9, 9, 9)
                                .addComponent(D3)
                                .addGap(9, 9, 9)
                                .addComponent(D4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(E0)
                                .addGap(9, 9, 9)
                                .addComponent(E1)
                                .addGap(9, 9, 9)
                                .addComponent(E2)
                                .addGap(9, 9, 9)
                                .addComponent(E3)
                                .addGap(9, 9, 9)
                                .addComponent(E4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(F0)
                                .addGap(9, 9, 9)
                                .addComponent(F1)
                                .addGap(9, 9, 9)
                                .addComponent(F2)
                                .addGap(9, 9, 9)
                                .addComponent(F3)
                                .addGap(9, 9, 9)
                                .addComponent(F4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(G0)
                                .addGap(9, 9, 9)
                                .addComponent(G1)
                                .addGap(9, 9, 9)
                                .addComponent(G2)
                                .addGap(9, 9, 9)
                                .addComponent(G3)
                                .addGap(9, 9, 9)
                                .addComponent(G4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(H0)
                                .addGap(9, 9, 9)
                                .addComponent(H1)
                                .addGap(9, 9, 9)
                                .addComponent(H2)
                                .addGap(9, 9, 9)
                                .addComponent(H3)
                                .addGap(9, 9, 9)
                                .addComponent(H4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(I0)
                                .addGap(9, 9, 9)
                                .addComponent(I1)
                                .addGap(9, 9, 9)
                                .addComponent(I2)
                                .addGap(9, 9, 9)
                                .addComponent(I3)
                                .addGap(9, 9, 9)
                                .addComponent(I4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(J0)
                                .addGap(9, 9, 9)
                                .addComponent(J1)
                                .addGap(9, 9, 9)
                                .addComponent(J2)
                                .addGap(9, 9, 9)
                                .addComponent(J3)
                                .addGap(9, 9, 9)
                                .addComponent(J4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(K0)
                                .addGap(9, 9, 9)
                                .addComponent(K1)
                                .addGap(9, 9, 9)
                                .addComponent(K2)
                                .addGap(9, 9, 9)
                                .addComponent(K3)
                                .addGap(9, 9, 9)
                                .addComponent(K4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L0)
                                .addGap(9, 9, 9)
                                .addComponent(L1)
                                .addGap(9, 9, 9)
                                .addComponent(L2)
                                .addGap(9, 9, 9)
                                .addComponent(L3)
                                .addGap(9, 9, 9)
                                .addComponent(L4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(M0)
                                .addGap(9, 9, 9)
                                .addComponent(M1)
                                .addGap(9, 9, 9)
                                .addComponent(M2)
                                .addGap(9, 9, 9)
                                .addComponent(M3)
                                .addGap(9, 9, 9)
                                .addComponent(M4))
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(N0)
                        .addGap(9, 9, 9)
                        .addComponent(N1)
                        .addGap(9, 9, 9)
                        .addComponent(N2)
                        .addGap(9, 9, 9)
                        .addComponent(N3)
                        .addGap(9, 9, 9)
                        .addComponent(N4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(O0)
                                .addGap(9, 9, 9)
                                .addComponent(O1)
                                .addGap(9, 9, 9)
                                .addComponent(O2)
                                .addGap(9, 9, 9)
                                .addComponent(O3)
                                .addGap(9, 9, 9)
                                .addComponent(O4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(P0)
                                .addGap(9, 9, 9)
                                .addComponent(P1)
                                .addGap(9, 9, 9)
                                .addComponent(P2)
                                .addGap(9, 9, 9)
                                .addComponent(P3)
                                .addGap(9, 9, 9)
                                .addComponent(P4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Q0)
                                .addGap(9, 9, 9)
                                .addComponent(Q1)
                                .addGap(9, 9, 9)
                                .addComponent(Q2)
                                .addGap(9, 9, 9)
                                .addComponent(Q3)
                                .addGap(9, 9, 9)
                                .addComponent(Q4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(R0)
                                .addGap(9, 9, 9)
                                .addComponent(R1)
                                .addGap(9, 9, 9)
                                .addComponent(R2)
                                .addGap(9, 9, 9)
                                .addComponent(R3)
                                .addGap(9, 9, 9)
                                .addComponent(R4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(S0)
                                .addGap(9, 9, 9)
                                .addComponent(S1)
                                .addGap(9, 9, 9)
                                .addComponent(S2)
                                .addGap(9, 9, 9)
                                .addComponent(S3)
                                .addGap(9, 9, 9)
                                .addComponent(S4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(T0)
                                .addGap(9, 9, 9)
                                .addComponent(T1)
                                .addGap(9, 9, 9)
                                .addComponent(T2)
                                .addGap(9, 9, 9)
                                .addComponent(T3)
                                .addGap(9, 9, 9)
                                .addComponent(T4)))))
                .addGap(4, 4, 4))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(317, 317, 317))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(295, 295, 295))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(A0)
                    .addComponent(A1)
                    .addComponent(A2)
                    .addComponent(A3)
                    .addComponent(A4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(B0)
                    .addComponent(B1)
                    .addComponent(B2)
                    .addComponent(B3)
                    .addComponent(B4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(C0)
                    .addComponent(C1)
                    .addComponent(C2)
                    .addComponent(C3)
                    .addComponent(C4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(D0)
                    .addComponent(D1)
                    .addComponent(D2)
                    .addComponent(D3)
                    .addComponent(D4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(E0)
                    .addComponent(E1)
                    .addComponent(E2)
                    .addComponent(E3)
                    .addComponent(E4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(F0)
                    .addComponent(F1)
                    .addComponent(F2)
                    .addComponent(F3)
                    .addComponent(F4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(G0)
                    .addComponent(G1)
                    .addComponent(G2)
                    .addComponent(G3)
                    .addComponent(G4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(H0)
                    .addComponent(H1)
                    .addComponent(H2)
                    .addComponent(H3)
                    .addComponent(H4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(I0)
                    .addComponent(I1)
                    .addComponent(I2)
                    .addComponent(I3)
                    .addComponent(I4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(J0)
                    .addComponent(J1)
                    .addComponent(J2)
                    .addComponent(J3)
                    .addComponent(J4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(K0)
                    .addComponent(K1)
                    .addComponent(K2)
                    .addComponent(K3)
                    .addComponent(K4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(L0)
                    .addComponent(L1)
                    .addComponent(L2)
                    .addComponent(L3)
                    .addComponent(L4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(M0)
                    .addComponent(M1)
                    .addComponent(M2)
                    .addComponent(M3)
                    .addComponent(M4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(N0)
                    .addComponent(N1)
                    .addComponent(N2)
                    .addComponent(N3)
                    .addComponent(N4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(O0)
                    .addComponent(O1)
                    .addComponent(O2)
                    .addComponent(O3)
                    .addComponent(O4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(P0)
                    .addComponent(P1)
                    .addComponent(P2)
                    .addComponent(P3)
                    .addComponent(P4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(Q0)
                    .addComponent(Q1)
                    .addComponent(Q2)
                    .addComponent(Q3)
                    .addComponent(Q4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(R0)
                    .addComponent(R1)
                    .addComponent(R2)
                    .addComponent(R3)
                    .addComponent(R4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(S0)
                    .addComponent(S1)
                    .addComponent(S2)
                    .addComponent(S3)
                    .addComponent(S4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(T0)
                    .addComponent(T1)
                    .addComponent(T2)
                    .addComponent(T3)
                    .addComponent(T4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A0ActionPerformed

    private void B0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B0ActionPerformed

    private void C0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C0ActionPerformed

    private void D0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D0ActionPerformed

    private void E0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E0ActionPerformed

    private void F0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F0ActionPerformed

    private void G0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G0ActionPerformed

    private void H0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_H0ActionPerformed

    private void I0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_I0ActionPerformed

    private void J0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J0ActionPerformed

    private void K0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_K0ActionPerformed

    private void L0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L0ActionPerformed

    private void M0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_M0ActionPerformed

    private void N0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_N0ActionPerformed

    private void O0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_O0ActionPerformed

    private void P0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P0ActionPerformed

    private void Q0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q0ActionPerformed

    private void R0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R0ActionPerformed

    private void S0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S0ActionPerformed

    private void T0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T0ActionPerformed

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        // TODO add your handling code here:
        if (A0.isSelected()) {
            CFR1 = 0;
        }
        else if (A1.isSelected()) {
            CFR1 = 0.4;
        }
        else if (A2.isSelected()) {
            CFR1 = 0.6;
        }
        else if (A3.isSelected()) {
            CFR1 = 0.8;
        }
        else if (A4.isSelected()) {
            CFR1 = 1;
        }
        
        if (B0.isSelected()) {
            CFR2 = 0;
        }
        else if (B1.isSelected()) {
            CFR2 = 0.4;
        }
        else if (B2.isSelected()) {
            CFR2 = 0.6;
        }
        else if (B3.isSelected()) {
            CFR2 = 0.8;
        }
        else if (B4.isSelected()) {
            CFR2 = 1;
        }
        
        if (C0.isSelected()) {
            CFR3 = 0;
        }
        else if (C1.isSelected()) {
            CFR3 = 0.4;
        }
        else if (C2.isSelected()) {
            CFR3 = 0.6;
        }
        else if (C3.isSelected()) {
            CFR3 = 0.8;
        }
        else if (C4.isSelected()) {
            CFR3 = 1;
        }
        
        if (D0.isSelected()) {
            CFR4 = 0;
        }
        else if (D1.isSelected()) {
            CFR4 = 0.4;
        }
        else if (D2.isSelected()) {
            CFR4 = 0.6;
        }
        else if (D3.isSelected()) {
            CFR4 = 0.8;
        }
        else if (D4.isSelected()) {
            CFR4 = 1;
        }
        
        if (E0.isSelected()) {
            CFR5 = 0;
        }
        else if (E1.isSelected()) {
            CFR5 = 0.4;
        }
        else if (E2.isSelected()) {
            CFR5 = 0.6;
        }
        else if (E3.isSelected()) {
            CFR5 = 0.8;
        }
        else if (E4.isSelected()) {
            CFR5 = 1;
        }
        
        if (F0.isSelected()) {
            CFR6 = 0;
        }
        else if (F1.isSelected()) {
            CFR6 = 0.4;
        }
        else if (F2.isSelected()) {
            CFR6 = 0.6;
        }
        else if (F3.isSelected()) {
            CFR6 = 0.8;
        }
        else if (F4.isSelected()) {
            CFR6 = 1;
        }
        
        if (G0.isSelected()) {
            CFR7 = 0;
        }
        else if (G1.isSelected()) {
            CFR7 = 0.4;
        }
        else if (G2.isSelected()) {
            CFR7 = 0.6;
        }
        else if (G3.isSelected()) {
            CFR7 = 0.8;
        }
        else if (G4.isSelected()) {
            CFR7 = 1;
        }
        
        if (H0.isSelected()) {
            CFR8 = 0;
        }
        else if (H1.isSelected()) {
            CFR8 = 0.4;
        }
        else if (H2.isSelected()) {
            CFR8 = 0.6;
        }
        else if (H3.isSelected()) {
            CFR8 = 0.8;
        }
        else if (H4.isSelected()) {
            CFR8 = 1;
        }
        
        if (I0.isSelected()) {
            CFR9 = 0;
        }
        else if (I1.isSelected()) {
            CFR9 = 0.4;
        }
        else if (I2.isSelected()) {
            CFR9 = 0.6;
        }
        else if (I3.isSelected()) {
            CFR9 = 0.8;
        }
        else if (I4.isSelected()) {
            CFR9 = 1;
        }
        
        if (J0.isSelected()) {
            CFR10 = 0;
        }
        else if (J1.isSelected()) {
            CFR10 = 0.4;
        }
        else if (J2.isSelected()) {
            CFR10 = 0.6;
        }
        else if (J3.isSelected()) {
            CFR10 = 0.8;
        }
        else if (J4.isSelected()) {
            CFR10 = 1;
        }
        
        if (K0.isSelected()) {
            CFR11 = 0;
        }
        else if (K1.isSelected()) {
            CFR11 = 0.4;
        }
        else if (K2.isSelected()) {
            CFR11 = 0.6;
        }
        else if (K3.isSelected()) {
            CFR11 = 0.8;
        }
        else if (K4.isSelected()) {
            CFR11 = 1;
        }
        
        if (L0.isSelected()) {
            CFR12 = 0;
        }
        else if (L1.isSelected()) {
            CFR12 = 0.4;
        }
        else if (L2.isSelected()) {
            CFR12 = 0.6;
        }
        else if (L3.isSelected()) {
            CFR12 = 0.8;
        }
        else if (L4.isSelected()) {
            CFR12 = 1;
        }
        
        if (M0.isSelected()) {
            CFR13 = 0;
        }
        else if (M1.isSelected()) {
            CFR13 = 0.4;
        }
        else if (M2.isSelected()) {
            CFR13 = 0.6;
        }
        else if (M3.isSelected()) {
            CFR13 = 0.8;
        }
        else if (M4.isSelected()) {
            CFR13 = 1;
        }
        
        if (N0.isSelected()) {
            CFR14 = 0;
        }
        else if (N1.isSelected()) {
            CFR14 = 0.4;
        }
        else if (N2.isSelected()) {
            CFR14 = 0.6;
        }
        else if (N3.isSelected()) {
            CFR14 = 0.8;
        }
        else if (N4.isSelected()) {
            CFR14 = 1;
        }
        
        if (O0.isSelected()) {
            CFR15 = 0;
        }
        else if (O1.isSelected()) {
            CFR15 = 0.4;
        }
        else if (O2.isSelected()) {
            CFR15 = 0.6;
        }
        else if (O3.isSelected()) {
            CFR15 = 0.8;
        }
        else if (O4.isSelected()) {
            CFR15 = 1;
        }
        
        if (P0.isSelected()) {
            CFR16 = 0;
        }
        else if (P1.isSelected()) {
            CFR16 = 0.4;
        }
        else if (P2.isSelected()) {
            CFR16 = 0.6;
        }
        else if (P3.isSelected()) {
            CFR16 = 0.8;
        }
        else if (P4.isSelected()) {
            CFR16 = 1;
        }
        
        if (Q0.isSelected()) {
            CFR17 = 0;
        }
        else if (Q1.isSelected()) {
            CFR17 = 0.4;
        }
        else if (Q2.isSelected()) {
            CFR17 = 0.6;
        }
        else if (Q3.isSelected()) {
            CFR17 = 0.8;
        }
        else if (Q4.isSelected()) {
            CFR17 = 1;
        }
        
        if (R0.isSelected()) {
            CFR18 = 0;
        }
        else if (R1.isSelected()) {
            CFR18 = 0.4;
        }
        else if (R2.isSelected()) {
            CFR18 = 0.6;
        }
        else if (R3.isSelected()) {
            CFR18 = 0.8;
        }
        else if (R4.isSelected()) {
            CFR18 = 1;
        }
        
        if (S0.isSelected()) {
            CFR19 = 0;
        }
        else if (S1.isSelected()) {
            CFR19 = 0.4;
        }
        else if (S2.isSelected()) {
            CFR19 = 0.6;
        }
        else if (S3.isSelected()) {
            CFR19 = 0.8;
        }
        else if (S4.isSelected()) {
            CFR19 = 1;
        }
        
        if (T0.isSelected()) {
            CFR20 = 0;
        }
        else if (T1.isSelected()) {
            CFR20 = 0.4;
        }
        else if (T2.isSelected()) {
            CFR20 = 0.6;
        }
        else if (T3.isSelected()) {
            CFR20 = 0.8;
        }
        else if (T4.isSelected()) {
            CFR20 = 1;
        }
        
        CF cf = new CF();
        gkNormal = cf.GKNormal(CFR1, CFR2, CFR3, CFR4, CFR5, CFR6, CFR11);
        gkBerminyak = cf.GKBerminyak(CFR7, CFR8, CFR9, CFR16);
        gkKering = cf.GKKering(CFR1, CFR5, CFR10, CFR11, CFR12);
        gkKombinasi = cf.GKKombinasi(CFR7, CFR14, CFR15, CFR16, CFR17);
        gkSensitif = cf.GKSensitif(CFR12, CFR18, CFR19, CFR20);
        
        new result(Nama, JK, gkNormal, gkBerminyak, gkKering, gkKombinasi, gkSensitif).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_resultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kuisioner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kuisioner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kuisioner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kuisioner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                kuisioner main = new kuisioner();
                main.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A0;
    private javax.swing.JRadioButton A1;
    private javax.swing.JRadioButton A2;
    private javax.swing.JRadioButton A3;
    private javax.swing.JRadioButton A4;
    private javax.swing.JRadioButton B0;
    private javax.swing.JRadioButton B1;
    private javax.swing.JRadioButton B2;
    private javax.swing.JRadioButton B3;
    private javax.swing.JRadioButton B4;
    private javax.swing.JRadioButton C0;
    private javax.swing.JRadioButton C1;
    private javax.swing.JRadioButton C2;
    private javax.swing.JRadioButton C3;
    private javax.swing.JRadioButton C4;
    private javax.swing.JRadioButton D0;
    private javax.swing.JRadioButton D1;
    private javax.swing.JRadioButton D2;
    private javax.swing.JRadioButton D3;
    private javax.swing.JRadioButton D4;
    private javax.swing.JRadioButton E0;
    private javax.swing.JRadioButton E1;
    private javax.swing.JRadioButton E2;
    private javax.swing.JRadioButton E3;
    private javax.swing.JRadioButton E4;
    private javax.swing.JRadioButton F0;
    private javax.swing.JRadioButton F1;
    private javax.swing.JRadioButton F2;
    private javax.swing.JRadioButton F3;
    private javax.swing.JRadioButton F4;
    private javax.swing.JRadioButton G0;
    private javax.swing.JRadioButton G1;
    private javax.swing.JRadioButton G2;
    private javax.swing.JRadioButton G3;
    private javax.swing.JRadioButton G4;
    private javax.swing.JRadioButton H0;
    private javax.swing.JRadioButton H1;
    private javax.swing.JRadioButton H2;
    private javax.swing.JRadioButton H3;
    private javax.swing.JRadioButton H4;
    private javax.swing.JRadioButton I0;
    private javax.swing.JRadioButton I1;
    private javax.swing.JRadioButton I2;
    private javax.swing.JRadioButton I3;
    private javax.swing.JRadioButton I4;
    private javax.swing.JRadioButton J0;
    private javax.swing.JRadioButton J1;
    private javax.swing.JRadioButton J2;
    private javax.swing.JRadioButton J3;
    private javax.swing.JRadioButton J4;
    private javax.swing.JRadioButton K0;
    private javax.swing.JRadioButton K1;
    private javax.swing.JRadioButton K2;
    private javax.swing.JRadioButton K3;
    private javax.swing.JRadioButton K4;
    private javax.swing.JRadioButton L0;
    private javax.swing.JRadioButton L1;
    private javax.swing.JRadioButton L2;
    private javax.swing.JRadioButton L3;
    private javax.swing.JRadioButton L4;
    private javax.swing.JRadioButton M0;
    private javax.swing.JRadioButton M1;
    private javax.swing.JRadioButton M2;
    private javax.swing.JRadioButton M3;
    private javax.swing.JRadioButton M4;
    private javax.swing.JRadioButton N0;
    private javax.swing.JRadioButton N1;
    private javax.swing.JRadioButton N2;
    private javax.swing.JRadioButton N3;
    private javax.swing.JRadioButton N4;
    private javax.swing.JRadioButton O0;
    private javax.swing.JRadioButton O1;
    private javax.swing.JRadioButton O2;
    private javax.swing.JRadioButton O3;
    private javax.swing.JRadioButton O4;
    private javax.swing.JRadioButton P0;
    private javax.swing.JRadioButton P1;
    private javax.swing.JRadioButton P2;
    private javax.swing.JRadioButton P3;
    private javax.swing.JRadioButton P4;
    private javax.swing.JRadioButton Q0;
    private javax.swing.JRadioButton Q1;
    private javax.swing.JRadioButton Q2;
    private javax.swing.JRadioButton Q3;
    private javax.swing.JRadioButton Q4;
    private javax.swing.JRadioButton R0;
    private javax.swing.ButtonGroup R01;
    private javax.swing.ButtonGroup R02;
    private javax.swing.ButtonGroup R03;
    private javax.swing.ButtonGroup R04;
    private javax.swing.ButtonGroup R05;
    private javax.swing.ButtonGroup R06;
    private javax.swing.ButtonGroup R07;
    private javax.swing.ButtonGroup R08;
    private javax.swing.ButtonGroup R09;
    private javax.swing.JRadioButton R1;
    private javax.swing.ButtonGroup R10;
    private javax.swing.ButtonGroup R11;
    private javax.swing.ButtonGroup R12;
    private javax.swing.ButtonGroup R13;
    private javax.swing.ButtonGroup R14;
    private javax.swing.ButtonGroup R15;
    private javax.swing.ButtonGroup R16;
    private javax.swing.ButtonGroup R17;
    private javax.swing.ButtonGroup R18;
    private javax.swing.ButtonGroup R19;
    private javax.swing.JRadioButton R2;
    private javax.swing.ButtonGroup R20;
    private javax.swing.JRadioButton R3;
    private javax.swing.JRadioButton R4;
    private javax.swing.JRadioButton S0;
    private javax.swing.JRadioButton S1;
    private javax.swing.JRadioButton S2;
    private javax.swing.JRadioButton S3;
    private javax.swing.JRadioButton S4;
    private javax.swing.JRadioButton T0;
    private javax.swing.JRadioButton T1;
    private javax.swing.JRadioButton T2;
    private javax.swing.JRadioButton T3;
    private javax.swing.JRadioButton T4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton result;
    // End of variables declaration//GEN-END:variables
}
